# Generated by Django 3.1.3 on 2021-01-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allblogs',
            name='author',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
